### ISSUE TITLE
Inzidenze wert unvollständig bei einigen Städten

### ISSUE THREAD

**Issue by bernhard131313** [tzschies/incidence#1]
Hey, super Widget. Im iPhone X alles OK. Beim iPad Pro 2020 sieht's wie folgt aus. Allerdings nur bei einigen Städten. 

![image](https://user-images.githubusercontent.com/73721840/97786341-335ca800-1bab-11eb-9fa1-23080287d77d.jpeg)

**Comment by tzschies** [comment]
Sollte mit der neuesten Version behoben sein, die Inzidenz ist jetzt wieder deutlich größer und hat mehr Platz. Bitte mal prüfen.

**Comment by bernhard131313** [comment]
Alles ok. Danke, danke

**Comment by bernhard131313** [comment]
Hallo, kann ich nachvollziehen. Der grosse Trend geht weiter aufwärts. Ist aber gewöhnungsbedürftig. Danke und weiter so
