### ISSUE TITLE
Trend Pfeil fehlerhaft

### ISSUE THREAD

**Issue by bernhard131313** [tzschies/incidence#2]
Hallo, habe leider noch einen Isle entdeckt. Der Trend passt nicht. In meinem bsp war gestern 62,2. heute 59,0. Pfeil müsste nach unten zeigen. 
Im Ursprungs Script glaube ich, war der Issing auch enthalten. Ist inzwischen behoben. 

![image](https://user-images.githubusercontent.com/73721840/97790120-29946e00-1bc6-11eb-860b-1c1c156ef8db.jpeg)

**Comment by bernhard131313** [comment]
Hier das Widget von heute von kevinkub. 
Die balkendarstellung von deinem Widget ist aber das beste. 

Wäre supi wenn man es korrigieren könnte

![image](https://user-images.githubusercontent.com/73721840/97790184-bb9c7680-1bc6-11eb-96c4-840f9840075a.jpeg)

**Comment by tzschies** [comment]
Mit der Trendauswertung bin ich auch noch nicht ganz zufrieden. 

Das Problem bei vielen Landkreisen ist einfach, dass am Wochenende nichts oder nur teilweise dem RKI gemeldet wird. Beispielhaft sieht man das hier an den "Dellen" (am Ende des orangen bzw. in der Mitte des roten Bereichs):
<img width="134" alt="verlauf" src="https://user-images.githubusercontent.com/67805460/97790428-db349e80-1bc8-11eb-9f29-f98b0fbf8566.png">
Aber wenn man sich die Kurve dieses Beispiels insgesamt anschaut, also über den gesamten Bereich, geht der Trend leider eindeutig nach oben. Deswegen finde ich eine tagesaktuelle Trendanzeige eher irreführend. 

Auf dein Beispiel bezogen: Dem RKI wurden gestern keine Daten gemeldet (592 Gesamtfälle am 29.10. und am 30.10.) Tagesaktuell müsste der Trendpfeil nach unten gehen. Aber die Verbreitung hat sich tatsächlich ja nicht beruhigt, nur weil an einem Tag mal nichts gemeldet wird. 
Ich hab mal beim LR ERH nachgeschaut: https://www.erlangen-hoechstadt.de/aktuelles/meldungen/neuartiges-corona-virus-sars-cov-2/
20 Neue Fälle, sowie eine Inzidenz von 73,6 wurden da heute gemeldet, die dann (wenn korrekt übertragen) morgen, ansonsten sogar erst übermorgen in der Statistik auftauchen sollte. 
Ein sinkender Pfeil heute stimmt also zwar mit den im Moment zur Verfügung stehenden Zahlen überein (von 62 auf 59), stimmt aber nicht mit dem tatsächlichen Trend überein (Steigerung auf über 73). 

Ich bin der Meinung, eine Trendermittlung kann nicht tagesaktuell durchgeführt werden. Ich bin deswegen dazu übergegangen, den Trend so zu bestimmen: Der Trend steigt, wenn der Wert von gestern größer ist als der Wert von vor einer Woche (!). 
Wie gesagt ganz zufrieden bin ich damit auch noch nicht, aber für mich sollte der Trendpfeil den Trend der letzten Tage bzw. der letzten Woche anzeigen.

**Comment by bernhard131313** [comment]
Hallo,

 

 kannst du mir kurz helfen und einen Hinweis geben wo ich Dein overviewCases.js finden kann. 

Ich kann kein Repositorie mit dem namen finden.

 

Gruß

 

Von: tzschies <notifications@github.com>
Antworten an: tzschies/incidence <reply@reply.github.com>
Datum: Samstag, 31. Oktober 2020 um 23:06
An: tzschies/incidence <incidence@noreply.github.com>
Cc: Bernhard-Höppner <bernhard.bernhard@t-online.de>, Author <author@noreply.github.com>
Betreff: Re: [tzschies/incidence] Trend Pfeil fehlerhaft (#2)

 

Mit der Trendauswertung bin ich auch noch nicht ganz zufrieden.

Das Problem bei vielen Landkreisen ist einfach, dass am Wochenende nichts oder nur teilweise dem RKI gemeldet wird. Beispielhaft sieht man das hier an den "Dellen" (am Ende des orangen bzw. in der Mitte des roten Bereichs):

Aber wenn man sich die Kurve dieses Beispiels insgesamt anschaut, also über den gesamten Bereich, geht der Trend leider eindeutig nach oben. Deswegen finde ich eine tagesaktuelle Trendanzeige eher irreführend.

Auf dein Beispiel bezogen: Dem RKI wurden gestern keine Daten gemeldet (592 Gesamtfälle am 29.10. und am 30.10.) Tagesaktuell müsste der Trendpfeil nach unten gehen. Aber die Verbreitung hat sich tatsächlich ja nicht beruhigt, nur weil an einem Tag mal nichts gemeldet wird.
Ich hab mal beim LR ERH nachgeschaut: https://www.erlangen-hoechstadt.de/aktuelles/meldungen/neuartiges-corona-virus-sars-cov-2/
20 Neue Fälle, sowie eine Inzidenz von 73,6 wurden da heute gemeldet, die dann (wenn korrekt übertragen) morgen, ansonsten sogar erst übermorgen in der Statistik auftauchen sollte.
Ein sinkender Pfeil heute stimmt also zwar mit den im Moment zur Verfügung stehenden Zahlen überein (von 62 auf 59), stimmt aber nicht mit dem tatsächlichen Trend überein (Steigerung auf über 73).

Ich bin der Meinung, eine Trendermittlung kann nicht tagesaktuell durchgeführt werden. Ich bin deswegen dazu übergegangen, den Trend so zu bestimmen: Der Trend steigt, wenn der Wert von gestern größer ist als der Wert von vor einer Woche (!).
Wie gesagt ganz zufrieden bin ich damit auch noch nicht, aber für mich sollte der Trendpfeil den Trend der letzten Tage bzw. der letzten Woche anzeigen.

**Comment by tzschies** [comment]
Auch hier im Repo 
Link zum Code 
https://github.com/tzschies/incidence/blob/main/overviewCases.js

**Comment by Herbyessen** [comment]
> Ich bin der Meinung, eine Trendermittlung kann nicht tagesaktuell durchgeführt werden. Ich bin deswegen dazu übergegangen, den Trend so zu bestimmen: Der Trend steigt, wenn der Wert von gestern größer ist als der Wert von vor einer Woche (!).

Wie wäre es mit dem Durchschnitt der letzten Woche ? Würde zu Deiner Statistik-Anzeige passen, oder?
