### ISSUE TITLE
Widget Gallery

### ISSUE THREAD

**Issue by dennerforen** [tzschies/incidence#3]
Hi Tzschies, Der scriptable Entwickler bringt eine Widget Gallery, ähnlich Apples Gallery für Kurzbefehle mit dem nächsten Update. Damit erreicht man ein mio Publikum.  

Er hat ein online Formular, in dem man sein Widget einreichen kann. 

Edit Link korrigiert

https://www.iphone-ticker.de/scriptable-app-mit-galerie-einfacher-zum-eigenen-widget-165478/

**Comment by mesche** [comment]
Direktlink: https://gallery.scriptable.app/submit

**Comment by tzschies** [comment]
Danke, ich werde es mir mal anschauen! :-)
