### ISSUE TITLE
Statistik-Anzeige funktioniert nicht mehr

### ISSUE THREAD

**Issue by Icebird2000** [tzschies/incidence#6]
An dieser Stelle sollte zwischen Statistik und Kurvenanzeige umgeschaltet werden was nun fehlschlägt.  
https://github.com/tzschies/incidence/blob/329a70c9c8004d5d170f0f4dc8ab59b9a5b72052/incidence.js#L120

**Comment by tzschies** [comment]
Hatte Änderungen übernommen, die ich nicht geprüft habe. Hab die jetzt erstmal komplett rückgängig gemacht, sollte jetzt wieder gehen. Bitte prüfen :-)

**Comment by Icebird2000** [comment]
Geht wieder. Danke

**Comment by mesche** [comment]
Problem hierbei:

Die Variable "parameters" enthält Strings.
Somit verlässt man sich hier darauf, dass JavaScript korrekt konvertiert.

`if (parameters[0] == 1) {`

Aus Entwicklungssicht nicht ganz optimal und ggf. gefährlich, da 1 auch als "true" und 0 als "false" interpretiert werden kann.

**Comment by Icebird2000** [comment]
Da magst du recht haben. Jedoch wird an dieser Stelle entschieden, ob eine Statistik oder ein Graph gezeichnet werden soll. Bei deinen Ergänzungen gibt es aber keinen solchen „Schalter“ mehr. 
(Ich glaube das das genau so gemeint war mit dem 1=true und 0=false)
