### ISSUE TITLE
Lungensymbol wird nicht richtig angezeigt

### ISSUE THREAD

**Issue by Icebird2000** [tzschies/incidence#7]
Eventuell ist dies ein Problem mit der Zeichencodierung von Github 
https://github.com/tzschies/incidence/blob/286f05d3b4928af9ddf10bbc776c789a757f1e86/overviewCases.js#L427
![AC87680B-6F36-43B8-80A2-38C22D4DE6AB](https://user-images.githubusercontent.com/1193280/98043205-234ffd00-1e25-11eb-8a8f-133bc84a2b87.jpeg)

**Comment by tzschies** [comment]
Es kann sein, dass das nur mit iOS 14.2 korrekt angezeigt wird. Welche Version verwendest Du?

**Comment by Icebird2000** [comment]
Habe noch 14.1 auf dem iPhone. Dann warten wir mal auf 14.2 😉

**Comment by emeff68** [comment]
Und jetzt geht's auch mit der Lunge. Perfekt!
